$(document).ready(function () {
    $("#form").validate({
        success:function (label) {
            label.addClass("checked");
        },
        rules:{
            username:{
                required:true,
                rangelength:[3,10]
            },
            password:{
                required:true,
                rangelength:[6,12]
            },
            qrpassword:{
                required:true,
                equalTo:"#password"
            },
            email:{
                required:true,
                email:true
            },
            tel:{
                required:true,
                isPhoneNo:true
            },
            sfz:{
                required:true,
                isIdCardNo:true
            },
            niche:{
                required:true,
                chcharacter:true
            }
        },
        messages:{
            username:{
                required:"请输入用户名",
                rangelength:"长度为3-10"
            },
            password:{
                required:"请输入密码",
                rangelength:"长度为6-12"
            },
            qrpassword:{
                required:"请输入密码",
                equalTo:"请与密码保持一致"
            },
            email:{
                required:"请输入邮箱地址",
                email:"请输入正确的邮箱地址"
            },
            tel:{
                required:"请输入手机号",
                isPhoneNo:"请输入正确的"
            },
            sfz:{
                required:"请输入身份证号码",
                isIdCardNo:"请输入正确的身份证号码"
            },
            niche:{
                required:"请输入昵称",
                chcharacter:"请输入汉字"
            }
        }
    })
});